export default [
  // CEXes
  'ASCENDEX',
  'OKX',
  'BINANCE',
  'KUCOIN',
  'ORION', // Internal
  'INTERNAL_ORDER_BOOK',

  // DEXes
  'SPOOKYSWAP',
  'PANCAKESWAP',
  'UNISWAP',
  'QUICKSWAP',
  'ORION_POOL',
  'INTERNAL_POOL_V2',
  'INTERNAL_POOL_V3',
  'INTERNAL_POOL_V3_0_01',
  'INTERNAL_POOL_V3_0_05',
  'INTERNAL_POOL_V3_0_3',
  'INTERNAL_POOL_V3_1_0',
  'CHERRYSWAP',
  'OKXSWAP',
  'CURVE',
  'CURVE_FACTORY',
  'THENA_ALGEBRA_V1',
] as const;
