enum SubscriptionType {
  ASSET_PAIRS_CONFIG_UPDATES_SUBSCRIBE = 'apcus',
  AGGREGATED_ORDER_BOOK_UPDATES_SUBSCRIBE = 'aobus',
  ADDRESS_UPDATES_SUBSCRIBE = 'aus',
  BROKER_TRADABLE_ATOMIC_SWAP_ASSETS_BALANCE_UPDATES_SUBSCRIBE = 'btasabus',
}

export default SubscriptionType;
