const SubscriptionType = {
  ASSET_PAIRS_CONFIG_UPDATES_SUBSCRIBE: 'apcus',
  ASSET_PAIR_CONFIG_UPDATES_SUBSCRIBE: 'apius',
  AGGREGATED_ORDER_BOOK_UPDATES_SUBSCRIBE: 'aobus',
  ADDRESS_UPDATES_SUBSCRIBE: 'aus',
  BROKER_TRADABLE_ATOMIC_SWAP_ASSETS_BALANCE_UPDATES_SUBSCRIBE: 'btasabus',
  SWAP_SUBSCRIBE: 'ss',
} as const;

export default SubscriptionType;
